advanceDjango/src/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [

	url(r'^$',views.SchoolListView.as_view(),name='list'),
	url(r'^(?P<pk>[-\w]+)/$',views.SchoolDetailView.as_view(),name='detail')


]
# Create your tests here.

advanceDjango/src/tryten/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [

    url(r'^$',views.IndexView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app'))
]

advanceDjango/src/basic_app/models.py
from django.db import models

class School(models.Model):
	name = models.CharField(max_length=256)
	principal = models.CharField(max_length=256)
	location = models.CharField(max_length=256)

	def __str__(self):
		return self.name

class Student(models.Model):
	name = models.CharField(max_length=256)
	age = models.PositiveIntegerField()
	school = models.ForeignKey(School,related_name='students')

	def __str__(self):
		return self.name
# Create your models here.

advanceDjango/src/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView
from . import models

class IndexView(TemplateView):
	template_name = 'index.html'

	#def get_context_data(self,**kwargs):
		#context = super().get_context_data(**kwargs)
		#context['injectme'] = 'BASIC INJECTION'
		#return  context

class SchoolListView(ListView):
	context_object_name = 'schools' 
	model = models.School

class SchoolDetailView(DetailView):
	context_object_name = 'school_detail'
	model = models.School
	template_name = 'basic_app/school_detail.html'

advanceDjango/src/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
<head>
	<title> index </title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>


<nav class = "navbar navbar-default navbar-static-top">
<ul class = "nav navbar-nav">
	<li><a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a></li>
	<li><a class="navbar-link" href="{% url 'admin:index' %}"> Admin</a> </li>
<li><a href="#"></a></li>
</ul>	

</nav>


<div class ="container">
 {% block body_block%}
 {% endblock %}
 </div>
</body>
</html>

advanceDjango/src/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html'%}
{% block body_block %}

<div class="jumbotron">
<h1>welcome to the school detail page</h1>
<h2>School details:</h2>
<p>Name: {{school_detail.principal }}</p>
<p>Principal: {{school_detail.praincipal }}</p>
<P>Location: {{school_detail.location }}</P> 
<h3>Students:</h3>

{% for student in school_detail.students.all %}
<p>{{student.name}} who is {{student.age}} years old.</p>
{% endfor %}

</div>
{% endblock %}

advanceDjango/src/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block %}

<h1>welcoe to the list of all the school</h1>
<ol>
{% for school in schools %}

<h2><li><a href="{{school.id}}"> {{school.name}}</a></li></h2>
{% endfor %}

</ol> 
{% endblock %}

advanceDjango/src/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title> index </title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>


<nav class = "navbar navbar-default navbar-static-top">
<ul class = "nav navbar-nav">
	<li><a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a></li>
	<li><a class="navbar-link" href="{% url 'admin:index' %}"> Admin</a> </li>
<li><a href="#"></a></li>
</ul>	

</nav>


<div class ="container">
 {% block body_block%}
 {% endblock %}
 </div>
</body>
</html>

advanceDjango/src/templates/index.html
{% extends "base.html" %}
{% block body_block%}
<div class = "jjumbotron">
<h1>HOme page</h1>
</div>
 {% endblock %}
 